export const contactConfig = {
  headline: "READY TO TAKE YOUR BUSINESS ONLINE?",
  subtitle: "Let's build your complete digital growth engine. Get in touch for a bespoke strategy session.",
  whatsappNumber: "+91 9457727770",
  whatsappDigits: "919457727770",
  whatsappUrl: "https://wa.me/919457727770?text=Hello%20VANIX%2C%20I%20would%20like%20to%20schedule%20a%20digital%20growth%20consultation%20for%20my%20business.",
  phone: "+91 9457727770",
  phoneRaw: "+919457727770",
  email: "hackwithkunal@gmail.com",
  location: "Shamli, Uttar Pradesh - 247776, India",
  linkedin: "https://linkedin.com/in/kunal-rajput-64b4002b4",
  youtube: "https://www.youtube.com/@HackWithKunal",
  youtubeHandle: "@HackWithKunal",
  businessTypes: [
    "Retail & Boutique Store",
    "Manufacturer / Factory",
    "Wholesaler / Distributor",
    "Local Service Provider",
    "D2C Brand / Creator",
    "Professional Firm",
    "Other Traditional Business",
  ],
  servicesOfInterest: [
    "Complete Digital Growth Engine (Recommended)",
    "Website / E-Commerce Development",
    "Amazon, Meesho & Marketplace Listing",
    "Google Maps & Local SEO",
    "Google & Meta Ads + WhatsApp Funnels",
    "Lead Generation & CRM Automation",
  ],
};
