export interface ServiceItem {
  id: string;
  number: string;
  title: string;
  category: "Foundation" | "Discovery" | "Acquisition" | "Operations" | "Strategy";
  shortDescription: string;
  fullDescription: string;
  deliverables: string[];
  iconName: string;
  accentImage?: string;
  videoLinkIndex?: number;
}

export const servicesData: ServiceItem[] = [
  {
    id: "website-development",
    number: "01",
    title: "Website Development",
    category: "Foundation",
    shortDescription: "Bespoke, blazing-fast responsive websites engineered for brand authority and lead conversion.",
    fullDescription: "We build custom, modern web applications tailored specifically to showcase your offline business, establish unmatched trust, and guide visitors seamlessly toward becoming paying customers.",
    deliverables: ["Custom UI/UX Design", "Mobile-first Responsive Architecture", "Speed & Core Web Vitals Optimization", "CMS Integration"],
    iconName: "Globe",
    accentImage: "/images/vanix-02.png",
  },
  {
    id: "e-commerce",
    number: "02",
    title: "E-Commerce Website",
    category: "Foundation",
    shortDescription: "Full-scale direct-to-consumer online stores with secure checkouts and inventory management.",
    fullDescription: "Take your retail or wholesale catalog online with a high-conversion e-commerce platform equipped with automated tax calculations, payment gateway integrations, and instant checkout.",
    deliverables: ["Payment Gateway Setup", "Cart Abandonment Funnels", "Product Variations & Inventory", "Order Management Dashboard"],
    iconName: "ShoppingCart",
    accentImage: "/images/vanix-03.png",
  },
  {
    id: "product-listing",
    number: "03",
    title: "Product Listing & Cataloging",
    category: "Discovery",
    shortDescription: "High-converting product listings with 3D product visuals, A+ content, and search indexing.",
    fullDescription: "Showcase your physical products with professional photography, benefit-driven copywriting, SEO-rich titles, and category tagging that captures shopper intent.",
    deliverables: ["A+ Content & Infographics", "SKU & Variation Architecture", "Attribute Optimization", "Keyword-Rich Descriptions"],
    iconName: "Layers",
    accentImage: "/images/vanix-04.png",
  },
  {
    id: "marketplaces",
    number: "04",
    title: "Amazon, Meesho & IndiaMART",
    category: "Discovery",
    shortDescription: "Multi-marketplace onboarding, brand registry, listing optimization, and sales management.",
    fullDescription: "Expand your reach onto India's largest marketplace platforms for both B2C and B2B orders. We handle end-to-end account management, catalog sync, and sponsored ads.",
    deliverables: ["Seller Account Setup & Verification", "Amazon Brand Registry & A+ Pages", "Meesho Catalog Launch", "IndiaMART Verified Lead Pipeline"],
    iconName: "Store",
    accentImage: "/images/vanix-04.png",
  },
  {
    id: "google-business-profile",
    number: "05",
    title: "Google Business Profile",
    category: "Discovery",
    shortDescription: "Verified Google Business Profile setup, optimization, and local map pack dominance.",
    fullDescription: "Make your business the first choice for local customers. We optimize your Google Maps listing with verified details, geotagged photos, business hours, and review collection.",
    deliverables: ["Profile Verification & Optimization", "Google Maps 3-Pack Strategy", "Automated Review Engine", "Weekly Posts & Catalog Updates"],
    iconName: "MapPin",
    accentImage: "/images/vanix-05.png",
  },
  {
    id: "local-seo",
    number: "06",
    title: "Local SEO & Geo-Targeting",
    category: "Discovery",
    shortDescription: "Targeted local search engine optimization to capture high-intent buyers in your city.",
    fullDescription: "Win local search queries with citations across high-authority directories, localized landing pages, schema markup, and regional keyword positioning.",
    deliverables: ["Local Directory Citations", "City-Specific Landing Pages", "Local Schema Markup", "Keyword Rank Tracking"],
    iconName: "Search",
    accentImage: "/images/vanix-05.png",
  },
  {
    id: "social-media-management",
    number: "07",
    title: "Social Media Management",
    category: "Acquisition",
    shortDescription: "Premium visual storytelling and brand building across Instagram, Facebook, and LinkedIn.",
    fullDescription: "Turn social media into a brand equity generator. We create luxury-grade graphics, video reels, and educational carousels that position your business as the market leader.",
    deliverables: ["High-Production Content Creation", "Brand Guidelines & Visual System", "Reels & Short-Form Video Strategy", "Community & Comment Management"],
    iconName: "Share2",
    accentImage: "/images/vanix-01.png",
  },
  {
    id: "google-ads",
    number: "08",
    title: "Google Ads (Search & Performance Max)",
    category: "Acquisition",
    shortDescription: "High-intent paid search campaigns delivering qualified inquiries from people ready to buy.",
    fullDescription: "Capture immediate demand. We structure tightly targeted Google Search and Performance Max campaigns, negative keyword lists, and ad copies designed to minimize cost per lead.",
    deliverables: ["Keyword Intent Research", "Ad Copywriting & A/B Testing", "Conversion Tracking Setup", "Continuous Bid & Negative Optimization"],
    iconName: "Target",
  },
  {
    id: "meta-ads",
    number: "09",
    title: "Meta Ads (Instagram & Facebook)",
    category: "Acquisition",
    shortDescription: "Laser-targeted demographic and interest campaigns that generate consistent demand.",
    fullDescription: "Reach ideal prospective customers where they spend their time. We produce high-converting video and carousel ads that drive traffic straight into your WhatsApp or lead forms.",
    deliverables: ["Audience Targeting & Retargeting", "Creative Video & Image Ad Production", "Server-Side CAPI Tracking", "ROAS Optimization"],
    iconName: "Flame",
  },
  {
    id: "whatsapp-sales",
    number: "10",
    title: "WhatsApp Sales & Commerce",
    category: "Acquisition",
    shortDescription: "Direct Click-to-WhatsApp funnels and automated catalogs for instant customer conversions.",
    fullDescription: "WhatsApp is where Indian business happens. We build automated product catalogs, instant response bots, and one-click chat triggers to convert conversations into confirmed orders.",
    deliverables: ["WhatsApp Business API Setup", "Direct Click-to-WhatsApp Ads", "Automated Catalog & Fast Replies", "Broadcast & Follow-up Workflows"],
    iconName: "MessageCircle",
    accentImage: "/images/vanix-06.png",
  },
  {
    id: "lead-generation",
    number: "11",
    title: "Lead Generation & CRM Automation",
    category: "Operations",
    shortDescription: "Automated qualification funnels and CRM routing that deliver warm, verified inquiries.",
    fullDescription: "Stop chasing unqualified prospects. We implement interactive lead qualification forms that filter serious buyers and route high-value inquiries directly to your phone.",
    deliverables: ["High-Converting Landing Pages", "Lead Qualification Scoring", "Instant SMS/WhatsApp Alerts", "CRM Pipeline Setup"],
    iconName: "UserCheck",
    accentImage: "/images/vanix-07.png",
  },
  {
    id: "analytics-reporting",
    number: "12",
    title: "Analytics & Growth Reporting",
    category: "Operations",
    shortDescription: "Crystal-clear growth dashboards tracking every metric from cost per click to net revenue.",
    fullDescription: "Eliminate guesswork. Our comprehensive reporting dashboards give you a 24/7 transparent view of traffic, leads, sales, return on ad spend, and customer acquisition costs.",
    deliverables: ["Custom Live Dashboard", "GA4 & Server-Side Event Tracking", "Monthly Executive Growth Reviews", "Attribution & ROAS Audits"],
    iconName: "BarChart3",
    accentImage: "/images/vanix-08.png",
  },
  {
    id: "online-growth-strategy",
    number: "13",
    title: "Online Growth Strategy",
    category: "Strategy",
    shortDescription: "Holistic digital roadmap connecting branding, channels, pricing, and scaling mechanics.",
    fullDescription: "We don't just provide isolated tools; we design your overarching digital growth system. A clear roadmap tailored to your specific offline strengths, market competitors, and unit economics.",
    deliverables: ["Competitive Market Analysis", "Multi-Channel Growth Roadmap", "Pricing & Offer Strategy", "Quarterly Expansion Milestones"],
    iconName: "Compass",
    accentImage: "/images/vanix-09.png",
  },
  {
    id: "technical-marketing-support",
    number: "14",
    title: "Technical & Marketing Support",
    category: "Strategy",
    shortDescription: "Dedicated technical and creative support to keep your digital systems operating at peak performance.",
    fullDescription: "Your digital engine requires continuous monitoring, security updates, and creative refreshes. We act as your dedicated growth and technology department.",
    deliverables: ["24/7 Uptime & Security Monitoring", "Regular Content & Listing Updates", "Dedicated Growth Manager", "Priority Technical Troubleshooting"],
    iconName: "ShieldCheck",
  },
];
